Repository Power-Components/livewire-powergrid, pull requests merged in 2024-02, with the labels that each got.

#1364 Add `Footer::pageName`
  resources/views/components/frameworks/bootstrap5/pagination.blade.php
  resources/views/components/frameworks/tailwind/pagination.blade.php
  src/Footer.php
  src/ProcessDataSource.php
  tests/Concerns/Components/DishesCustomPageNameTable.php
  tests/Feature/PaginationTest.php
Labels: need docs

#1362 Queue export with dependencies
  composer.json
  phpstan.neon
  src/Concerns/Base.php
  src/Jobs/ExportJob.php
  src/PowerGridComponent.php
  src/ProcessDataSource.php
  src/Traits/ExportableJob.php
  src/Traits/WithExport.php
  tests/Concerns/Components/BatchExportTable.php
  tests/Feature/BatchExportTest.php
Labels: need docs

#1397 [Cypress] - Filters select, select join
  tests/cypress/cypress/e2e/filters/input-text.cy.js
  tests/cypress/cypress/e2e/filters/number-join.cy.js
  tests/cypress/cypress/e2e/filters/number.cy.js
  tests/cypress/cypress/e2e/filters/select-join.cy.js
  tests/cypress/cypress/e2e/filters/select.cy.js
Labels: tests

#1396 [Feature] Unescape column titles to allow custom html to be shown
  resources/views/components/cols.blade.php
Labels: feature, need docs

#1387 [Feature] Persist `sorting`
  src/Concerns/Persist.php
  src/Concerns/Sorting.php
Labels: need docs
